### ISSUE TITLE
Mocking interface methods with total name longer than 30 characters doesn't work. 

### ISSUE THREAD

**Issue by lucastetreault** [uweku/mockA#11]
I am creating a mock for a class 'ZCL_RECEIVABLE_CALCULATOR_RBL' which implements an interface 'ZIF_CFSR_RECEIVABLE_CALCULATOR'. When I try to create a fake for the method 'ZIF_CFSR_RECEIVABLE_CALCULATOR~CALCULATE' the mock cuts the total method name off at 30 characters: 'ZIF_CFSR_RECEIVABLE_CALCULATOR~CAL' and generating the mock fails.

**Comment by uweku** [comment]
Thank you very much! I did some minor changes. Would you please try again?

**Comment by lucastetreault** [comment]
Hey, sorry I didn't get back to you any sooner. Everything is working :)
