### ISSUE TITLE
Method call with optional importing parameters

### ISSUE THREAD

**Issue by mwernli** [uweku/mockA#15]
Hi,
I am trying out this framework and so far I think it's very neat! Exactly what has been missing in ABAP. I have one question regarding optional / default value importing parameters.
It seems that the framework will register a call only for actually passed parameters, which I think is fine. But the IS SUPPLIED condition in the generated mock method returns false for parameters with default values. I think it should be registered though, because a default parameter is always passed even if (or particularly when) there is no actual parameter.
Secondly, the HAS_BEEN_CALLED_WITH method will build a method call with all parameters, regardless whether they are optional / have default values or not, and compares this to the actual method calls that have happenend. I don't see how this can condtion ever be fulfilled if I leave out optional parameters in the actaul implementation.
I hope the description of my problem is clear.. Did I miss something in the documentation (i.e. is this known / intended behaviour) or is this a bug?

Kind regards & thank you for this framework.
Max

**Comment by uweku** [comment]
Dear Max,

Thank you for your feedback. mockA should provide a functionality to verify method input specifically based on parameter names, but not based on sequence of parameters as this might get mixed up for optional parameetrs. 
There is no easy fix for that. You might want to use the test double framework for that. More information in
http://scn.sap.com/community/abap/blog/2016/02/07/abap-test-double-framework-versus-mocka
->"Let the framework ignore importing parameters"

Regards,

Uwe

**Comment by mwernli** [comment]
Hi Uwe
Okay,
thank you for your reply and the link, I will check out this test double framework when I have the time. For now I'll just rely on has_method_been_called and my coding skills ;)
I'm closing this issue, thanks again.
Greetings
