### ISSUE TITLE
Error during import repository

### ISSUE THREAD

**Issue by VanDerSam** [uweku/mockA#18]
I tried to import repository with ABAPGit. But in my system occurs the error:
![image](https://user-images.githubusercontent.com/8073670/38781252-c5272c86-40ea-11e8-8f51-4c3857fe2d23.png)
I analyzed this problem. Master language of repository is detected as DE. But in my system language is EN. Can you change default language to EN?

**Comment by uweku** [comment]
Would you please try again? I updated the master language field, maybe that helps already:
177f3193594cc9c27f9a411e65334b62e0f59825

**Comment by VanDerSam** [comment]
I tried it. There is the error now.
Thank you.
